apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: medusas.medusacontroller.k8s.io
spec:
  group: medusacontroller.k8s.io
  version: v1alpha1
  names:
    kind: Medusa
    plural: medusas
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            branchName:
              type: string
            currentSha:
              type: string  
            pusher:
              type: string  
            repoUrl:
              type: string
            repoName:
              type: string  
            destroy:
              type: bool  
            replicas:
              type: integer
              minimum: 1
              maximum: 10